### Lấy danh sách task
GET http://localhost:3001/api/tasks

###

### Tạo task
POST http://localhost:3001/api/tasks
Content-Type: application/json

{
  "title": "Học Express.js",
  "description": "Hoàn thành REST API",
  "priority": "high",
  "dueDate": "2026-08-20"
}

###

### Lấy task theo ID
GET http://localhost:3001/api/tasks/6a809bd0a461a6e920226acc

###

### Cập nhật task theo ID
PUT http://localhost:3001/api/tasks/6a809bd0a461a6e920226acc
Content-Type: application/json

{
  "title": "Học Express.js nâng cao",
  "description": "Hoàn thành REST API và MongoDB",
  "priority": "high",
  "dueDate": "2026-08-25"
}

###

### Xóa task theo ID
DELETE http://localhost:3001/api/tasks/6a809bd0a461a6e920226acc

###

### Cập nhật trạng thái 
PATCH http://localhost:3001/api/tasks/6a809bd0a461a6e920226acc/status
Content-Type: application/json

{
  "status": "done"
}